### ISSUE TITLE
DST calculation issues

### ISSUE THREAD

**Issue by ecwilliams** [ekondayan/micropython-ntp#4]
A couple of issues with daylight savings calculations:

1) In lines 301 and 302, dst() is passing dt[1] as the month argument to day_from_week_and_weekday().  This is the current month, but I believe it should instead be passing the months from _dst_start and _dst_end.

2) The method of specifying DST start/end is by ordinal week number and day of week.  This doesn't match national specifications for DST which refer to ordinal days of week in the month, which is not the same.  For example, USA says DST ends on the first Sunday in November, but if I specify with set_dst_end() the Sunday in the first week in November, day_from_week_and_weekday() will raise an exception because the first week of November 2023 does not include a Sunday.

I have written a substitute function for day_from_week_and_weekday() which calculates from ordinal weekdays that I can put in a pull request if you are interested.

**Comment by ekondayan** [comment]
Please create a PR so I can check your solution.

P.S. Sorry for the delay

**Comment by ekondayan** [comment]
PR merged
