### ISSUE TITLE
machine.RTC().datetime for ESP8266 (wemos D1) not compatible

### ISSUE THREAD

**Issue by martinkoehler** [ekondayan/micropython-ntp#7]
It seems that the library is not working correctly with the machine.RTC().datetime as a callback function in case the hardware is a wemos D1 mini board (ESP8266) and using the micropython board for the ESP8266 LOLIN_D1_MINI board.

The micropython doc states that the subsconds field for RTC().datetime is hardware dependent.
For the ESP8266 I observerd that the subseconds must be milli seconds (e.g. <1000). In case micro seconds are used, this is interpreted as seconds/minutes, ..., which sets the RTC to a completely false time during a rtc_sync
The same applies when applying drift_compensate. This can be fixed by defining the call back function as follows:
```
def datetime_callback(dt=None):
        import machine
        if (dt):
            # dt[7] are subseconds. In ntp these are us, for ESP8266 ms must be used
            dt = dt[0:7] + (dt[7]//1000,)
            machine.RTC().datetime(dt)
            return
        dt = machine.RTC().datetime()
        return dt[0:7] + (dt[7]*1000,)
```
I do not know, whether a genic fix in the ntp source code can be implemented?

**Comment by ekondayan** [comment]
Hi,
it's important to clarify that the callback function is designed to be user-defined and is not inherently a part of the library. This approach is intentional to ensure the library's compatibility with a wide range of hardware. The primary role of the callback function is to serve as a bridge between the specific RTC chip used in your hardware and the micropython-ntp library. This design choice allows for the micropython-ntp to remain chip-agnostic, providing broad compatibility and flexibility across various hardware platforms. For instance, you can create one callback function to synchronize a DS3231 chip, and another to sync the microcontroller's built-in RTC.

To address this, I will update the README file to include a note about this specific behavior on ESP8266 boards.

Thank you for highlighting this aspect.

**Comment by martinkoehler** [comment]
Hi,
thanks for your quick reply:
>it's important to clarify that the callback function is designed to be user-defined and is not inherently a part of the library. 

Yes, I understand. Updating the README file would be nice and the issue could be closed.

My idea was to handle this a bit like the EPOCH case, where we have different implementions:
Defining constants for 
e.g. 
```
SUBSECONDSDIVIDER_MS = 1000
SUBSECONDSDIVIDER_US = 1000_000 # Could be the default for cls._subseconddivder
```
and using
```
cls._datetime((lt[0], lt[1], lt[2], lt[6] + 1, lt[3], lt[4], lt[5], ntp_us % cls._subseconddivider))
```
would allow to use the micropython native `machine.RTC().datetime` function for any board, provided the  `_subseconddivder` is set correctly.

IMHO this might be a bit more userfriendly than writing a wrapper for the native micropython function if using a wemos D1 mini board :-)

But I'm of course fine with updating the doc.
... and thanks for sharing this nice library.

**Comment by ekondayan** [comment]
I like your idea. That would make the library more generic but this change could introduce additional complexity.
I was wondering if using a decorator can provide a neat way of adding this new feature while keeping it optional and unobtrusive for users who don’t require it.

**Comment by martinkoehler** [comment]
Yes, this sounds good. 
Do you have a decorator e.g. `use_subseconds_ms` defind as below or similar in mind?
```
# This can be part of ntp.py
def use_subseconds_ms(func):
    def inner(dt=None):
        if (dt):
            # dt[7] are subseconds. In ntp these are us, for ESP8266 ms must be used
            dt = dt[0:7] + (dt[7]//1000,)
            func(dt)
            return
        dt = func(dt)
        return dt[0:7] + (dt[7]*1000,)
    return inner

# This would be in the user code
@use_subseconds_ms
def datetime_callback(dt=None):
    import machine
    return machine.RTC().datetime(dt)

# or for a native function
cb = use_subseconds(machine.RTC().datetime)
```
I have not fully tested this :-(

**Comment by ekondayan** [comment]
May I ask you to test this decorator:
```
SUBSECOND_PRECISION_SEC = const(1000_000)
SUBSECOND_PRECISION_MS = const(1000)
SUBSECOND_PRECISION_US = const(1)

def subsecond_precision(precision):
    if precision not in (SUBSECOND_PRECISION_SEC, SUBSECOND_PRECISION_MS, SUBSECOND_PRECISION_US):
        raise ValueError('Invalid parameter: precision={} must be one of SUBSECOND_PRECISION_SEC, SUBSECOND_PRECISION_MS, SUBSECOND_PRECISION_US'.format(precision))
    def decorator(func):
        def inner(dt = None):
            if dt:
                func(dt[0:7] + (dt[7] // precision,))
                return
            dt = func(dt)
            return dt[0:7] + (dt[7] * precision,)

        return inner

    return decorator

@subsecond_precision(SUBSECOND_PRECISION_MS)
def datetime_callback(dt=None):
    import machine
    return machine.RTC().datetime(dt)
```

**Comment by martinkoehler** [comment]
Thanks. I've tested and corrected the code:
The following decorator and datetime_callback work for me:
```
def subsecond_precision(precision):
    if precision not in (SUBSECOND_PRECISION_SEC, SUBSECOND_PRECISION_MS, SUBSECOND_PRECISION_US):
        raise ValueError('Invalid parameter: precision={} must be one of SUBSECOND_PRECISION_SEC, SUBSECOND_PRECISION_MS, SUBSECOND_PRECISION_US'.format(precision))
    def decorator(func):
        def inner(*args):
            if (len(args) == 1):
                dt = args[0]
                return func(dt[0:7] + (dt[7] // precision,))
            dt = func()
            return dt[0:7] + (dt[7] * precision,)
        return inner
    return decorator

@subsecond_precision(SUBSECOND_PRECISION_MS)
def datetime_callback(*dt):
    import machine
    return machine.RTC().datetime(*dt)
```

NB: We need a `*args`, since e.g. `machine.RTC().datetime(None)` gives an error instead of returning the actual tuple. (My mistake in the code above. Sorry)

**Comment by ekondayan** [comment]
Hi,
I've pushed a new branch `issue-7`. May I ask you to test it and give me a feedback, so I can merge it into the main.

I've modified the `set_datetime_callback` to accept `precision` argument. This argument is the precision the callback works with.

Now you shall be able to do:
```python
import machine
Ntp.set_datetime_callback(machine.RTC().datetime, Ntp.SUBSECOND_PRECISION_MS)
```

I think this is the most user friendly approach. No custom callbacks. Backward compatible.

**Comment by martinkoehler** [comment]
Hi,
thanks a lot. I've tested the new code from the branch and it works as expected.
I agree that this is 
> the most user friendly approach. No custom callbacks. Backward compatible.

Thanks for implementing this.
IMHO this can be merged.

**Comment by ekondayan** [comment]
Merged. 

Thank you!
